#!/usr/bin/env python3
"""
Mirror ~/Obsidian/sync-blog/ -> docs/ and regenerate the sync-nav section in mkdocs.yml.

Also vendored at Obsidian/.github/scripts/sync-blog.py for CI — keep both identical.

Layout expected under --src (default ~/Documents/Obsidian/sync-blog):

    sync-blog/
      Blog/
        index.md          # section landing (source of truth)
        image/            # images; referenced as image/x.png by flat posts,
                          #                    ../image/x.png by category posts
        AWS/
          post.md         # category group
        flat-post.md      # flat entry under section root
      Engineering Patterns/
        index.md
        gitops.md         # flat entry
      <AnyFutureSection>/
        ...

Each top-level directory becomes one nav section.  Section names are used
verbatim as nav labels; folder name -> slug maps to docs/<slug>/.

Rules:
  - Top-level dir name -> slug: lowercase, spaces -> "-", underscores -> "-".
  - Skip dotfiles, .DS_Store, __pycache__, and the special names "image" and "posts".
  - Files named index.md at section root -> section landing page.
  - Other .md files at section root -> flat sidebar entries.
  - Subdirs at section root (except image/, posts/) -> category groups; .md
    files inside -> grouped entries.
  - Image embed conversion: ![[x.png]] -> ![](image/x.png) (flat) or
    ![]( ../image/x.png) (inside category subdir).
  - docs/.sync-manifest.json records managed slugs so stale dirs are cleaned
    up on subsequent runs.
  - mkdocs.yml sync-nav markers (sync-nav, not blog-nav) are required to
    exist before running.  One-time setup: add them manually once to main.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path


MARKER_START = "# >>> sync-nav (auto-generated by scripts/sync-blog.py - do not edit)"
MARKER_END = "# <<< sync-nav"
MANIFEST_PATH = "docs/.sync-manifest.json"

_SKIP_NAMES = {"image", "posts", ".DS_Store", "__pycache__"}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def slugify(name: str) -> str:
    """'Engineering Patterns' -> 'engineering-patterns'."""
    return re.sub(r"[\s_]+", "-", name.strip()).lower()


def human_title_from_stem(stem: str) -> str:
    s = stem.replace("-", " ").replace("_", " ")
    return s[:1].upper() + s[1:] if s else stem


def extract_title(md_text: str, stem: str) -> str:
    m = re.search(r"^title:\s*(.+)$", md_text, re.MULTILINE)
    if m:
        return m.group(1).strip().strip("\"'")
    m = re.search(r"^#\s+(.+)$", md_text, re.MULTILINE)
    if m:
        return m.group(1).strip()
    return human_title_from_stem(stem)


def convert_image_embeds(body: str, image_prefix: str) -> str:
    """Replace ![[foo.png]] with ![](image_prefix/foo.png)."""
    return re.sub(
        r"!\[\[([^\]|]+?)(?:\|[^\]]+)?\]\]",
        lambda m: f"![]({image_prefix}{m.group(1).strip()})",
        body,
    )


def is_section_dir(p: Path) -> bool:
    if not p.is_dir():
        return False
    if p.name.startswith("."):
        return False
    if p.name in _SKIP_NAMES:
        return False
    return True


def is_category_dir(p: Path) -> bool:
    if not p.is_dir():
        return False
    if p.name.startswith("."):
        return False
    if p.name in _SKIP_NAMES:
        return False
    return True


# ---------------------------------------------------------------------------
# Sync one section
# ---------------------------------------------------------------------------

def sync_section(src_section: Path, dst_section: Path, section_name: str) -> list[str]:
    """
    Sync one section dir.  Returns nav YAML lines (not indented) for this section.
    """
    slug = slugify(section_name)
    dst_section.mkdir(parents=True, exist_ok=True)

    # Remove category subdirs (re-generate below); keep index.md and image/
    for child in dst_section.iterdir():
        if child.is_dir() and child.name != "image":
            shutil.rmtree(child)
        elif child.is_file() and child.name != "index.md":
            child.unlink()

    # Images
    src_img = src_section / "image"
    dst_img = dst_section / "image"
    if src_img.is_dir():
        if dst_img.exists():
            shutil.rmtree(dst_img)
        shutil.copytree(src_img, dst_img)
    elif dst_img.exists():
        shutil.rmtree(dst_img)

    nav_lines: list[str] = []
    nav_lines.append(f'  - "{section_name}":')

    # Section index
    src_index = src_section / "index.md"
    dst_index = dst_section / "index.md"
    if src_index.exists():
        text = src_index.read_text(encoding="utf-8")
        text = convert_image_embeds(text, "image/")
        dst_index.write_text(text, encoding="utf-8")
    else:
        # Generate stub if missing
        if not dst_index.exists():
            dst_index.write_text(f"# {section_name}\n", encoding="utf-8")
    nav_lines.append(f"      - {slug}/index.md")

    # Flat posts (*.md at section root, excluding index.md)
    flat_posts = sorted(
        [p for p in src_section.iterdir() if p.is_file() and p.suffix.lower() == ".md" and p.name != "index.md"],
        key=lambda p: p.name.lower(),
    )
    for post in flat_posts:
        text = post.read_text(encoding="utf-8")
        text = convert_image_embeds(text, "image/")
        dst_file = dst_section / post.name
        dst_file.write_text(text, encoding="utf-8")
        title = extract_title(text, post.stem)
        safe_title = title.replace('"', '\\"')
        nav_lines.append(f'      - "{safe_title}": {slug}/{post.name}')

    # Category groups (subdirs)
    cat_dirs = sorted(
        [p for p in src_section.iterdir() if is_category_dir(p)],
        key=lambda p: p.name.lower(),
    )
    for cat_dir in cat_dirs:
        md_files = sorted(
            [p for p in cat_dir.iterdir() if p.is_file() and p.suffix.lower() == ".md"],
            key=lambda p: p.name.lower(),
        )
        if not md_files:
            continue
        dst_cat = dst_section / cat_dir.name
        dst_cat.mkdir(exist_ok=True)
        nav_lines.append(f'      - "{cat_dir.name}":')
        for md in md_files:
            text = md.read_text(encoding="utf-8")
            text = convert_image_embeds(text, "../image/")
            dst_file = dst_cat / md.name
            dst_file.write_text(text, encoding="utf-8")
            title = extract_title(text, md.stem)
            safe_title = title.replace('"', '\\"')
            nav_lines.append(f'          - "{safe_title}": {slug}/{cat_dir.name}/{md.name}')

    return nav_lines


# ---------------------------------------------------------------------------
# Main sync
# ---------------------------------------------------------------------------

def sync(src: Path, repo_root: Path) -> None:
    docs = repo_root / "docs"
    manifest_path = repo_root / MANIFEST_PATH

    # Load previous manifest to clean up removed sections
    prev_slugs: set[str] = set()
    if manifest_path.exists():
        try:
            prev_slugs = set(json.loads(manifest_path.read_text()).get("slugs", []))
        except Exception:
            pass

    section_dirs = sorted(
        [p for p in src.iterdir() if is_section_dir(p)],
        key=lambda p: p.name.lower(),
    )
    if not section_dirs:
        print(f"warning: no section directories found under {src}", file=sys.stderr)

    current_slugs: set[str] = set()
    all_nav_lines: list[str] = []

    for section_dir in section_dirs:
        section_name = section_dir.name
        slug = slugify(section_name)
        current_slugs.add(slug)
        dst_section = docs / slug
        nav_lines = sync_section(section_dir, dst_section, section_name)
        all_nav_lines.extend(nav_lines)

    # Clean up stale sections
    for stale_slug in prev_slugs - current_slugs:
        stale_dir = docs / stale_slug
        if stale_dir.is_dir():
            shutil.rmtree(stale_dir)
            print(f"removed stale section: {stale_dir}")

    # Save manifest
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps({"slugs": sorted(current_slugs)}, indent=2) + "\n",
        encoding="utf-8",
    )

    # Patch mkdocs.yml
    mkdocs_path = repo_root / "mkdocs.yml"
    text = mkdocs_path.read_text(encoding="utf-8")
    if MARKER_START not in text or MARKER_END not in text:
        print(
            "error: mkdocs.yml missing sync-nav markers.\n"
            "Add these two lines after the Projects nav block (once, manually):\n"
            f"  {MARKER_START}\n"
            f"  {MARKER_END}",
            file=sys.stderr,
        )
        sys.exit(1)

    before, rest = text.split(MARKER_START, 1)
    before = before.rstrip()
    _old, after = rest.split(MARKER_END, 1)

    nav_block = [f"  {MARKER_START}"]
    nav_block.extend(all_nav_lines)
    nav_block.append(f"  {MARKER_END}")

    mkdocs_path.write_text(
        before + "\n" + "\n".join(nav_block) + after,
        encoding="utf-8",
    )

    print(f"synced {len(section_dirs)} section(s): {', '.join(d.name for d in section_dirs)}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--src",
        type=Path,
        default=Path.home() / "Documents" / "Obsidian" / "sync-blog",
        help="Obsidian sync-blog parent directory",
    )
    ap.add_argument(
        "--repo",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="jiwool0920.github.io repo root",
    )
    args = ap.parse_args()
    sync(args.src.resolve(), args.repo.resolve())


if __name__ == "__main__":
    main()
